apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    role: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nginx
  template: 
    metadata:
        labels:
            role: nginx
    spec:
        containers:
        - name: nginx
          image: nadulang/nginx
          lifecycle:
            preStop:
                exec:
                    command: ["/usr/sbin/nginx","-s","quit"]